[profile.default]
solc_version = "0.8.25"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
verbosity = 3
isolate = true

[fmt]
tab_width = 2
bracket_spacing = true
number_underscore = "thousands"

[rpc_endpoints]
optimism = "${OPTIMISM_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
