[profile.default]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 999_999
deny_warnings = true
verbosity = 3
isolate = true
fs_permissions = [{ access = "read", path = "./broadcast" }]

[fmt]
tab_width = 2
sort_imports = true
bracket_spacing = true
number_underscore = "thousands"

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism_sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"

[etherscan]
base = { key = "${ETHERSCAN_KEY}" }
base_sepolia = { key = "${ETHERSCAN_KEY}" }
optimism = { key = "${ETHERSCAN_KEY}" }
optimism_sepolia = { key = "${ETHERSCAN_KEY}" }

[profile.legacy]
evm_version = "paris"
